### ISSUE TITLE
tagging a release (even RC/beta)?

### ISSUE THREAD

**Issue by sandrotosi** [mprovost/NFStash#19]
hey there! I'd like to package this project for Debian (i havent started yet), but we kinda prefer to base the packaging on an "official" release (even if it is only a release candidate/beta status), would you consider tagging one?

thanks in advance,
Sandro!

**Comment by mprovost** [comment]
No problem, it's not really a specific release point yet but I've been delaying that for a long time so I might as well at least tag it as 0.5 or something. Let me push a few more changes and then I'll tag it.

**Comment by sandrotosi** [comment]
nice!! thanks a lot for the super-quick answer!

**Comment by mprovost** [comment]
I just created an initial 0.5 release. Thanks!

**Comment by sandrotosi** [comment]
cool thanks! i've just pushed the package up for acceptance (as you might have guessed by the issues stream hehe)
