### ISSUE TITLE
dont include man/*.html in the released tarball

### ISSUE THREAD

**Issue by sandrotosi** [mprovost/NFStash#22]
hello! the man/*.html files are generated from the *.ronn files (and they are even removed in the `make clean` target), so please dont include them in the released tarball (or you can also consider remove them completely from the git repo)

thanks!

**Comment by mprovost** [comment]
The HTML files are being served from Github for documentation, that's why I
added them to the repo. Would it be easier if I also added the generated
manpages to the repo which would remove the dependency on ronn to generate
the documentation (unless you edit the ronn sources as a developer)?

**Comment by sandrotosi** [comment]
oh i see, i looked at nfping which has its own md file, and not the other links in the readme, that indeed point to those files.

i usally have a feel that the release tarball should contain only the source files, and regenerate everything from there, but i can live with either the keeping the html file as-is or adding the generated manpages to the tarball (ronn dependency is not a big issue, it's just another program to install when building NFStash)
