### ISSUE TITLE
IPv6 support possible?

### ISSUE THREAD

**Issue by hrodenburg** [mprovost/NFStash#26]
Hi,
I just came accross these tools, which looks really nice and helpful. However, we have our nfs servers running on IPv6 addresses only.  It seems that at least `nfsping` does not support IPv6, tried by hostname and address. In both cases it will return `getaddrinfo error ([<v6address>]): Name or service not known`. Is it possible to support ipv6 for these tools?

**Comment by mprovost** [comment]
Thanks for the feedback. Unfortunately I don't run IPv6 anywhere so I don't have an easy way to add support for it myself. Even if someone patched the code I wouldn't be able to test it or maintain it so I think forking the project and adding v6 support there would be the best way to get this done.
